package net.StrayBead.hbm_ntm.datagen;

import net.StrayBead.hbm_ntm.HBMNTM;
import net.StrayBead.hbm_ntm.block.ModBlocks;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.minecraftforge.common.data.BlockTagsProvider;
import net.minecraftforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagGenerator extends BlockTagsProvider {
    public ModBlockTagGenerator(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, @Nullable ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, HBMNTM.MOD_ID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.Provider provider) {
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE)
                .add(ModBlocks.THORIUM_ORE.get(),
                        ModBlocks.BERYLLIUM_ORE.get(),
                        ModBlocks.PLAYER_DECONTAMINATOR.get(),
                        ModBlocks.LEAD_ANVIL.get(),
                        ModBlocks.SIM_CARD_SIGNAL_BROADCASTING_DEVICE.get(),
                        ModBlocks.SHALLOW_FOUNDRY_BASIN.get(),
                        ModBlocks.MALACHITE.get(),
                        ModBlocks.HEMATITE.get(),
                        ModBlocks.SCHRABIDIUM_ORE.get(),
                        ModBlocks.STEEL_BLOCK.get(),
                        ModBlocks.POWER_SWITCH.get(),
                        ModBlocks.RED_COPPER_BLOCK.get(),
                        ModBlocks.BUNKER_DOOR.get(),
                        ModBlocks.STEEL_DECO_BLOCK.get(),
                        ModBlocks.LIGNITE_ORE.get(),
                        ModBlocks.ANTENNA_TOP.get(),
                        ModBlocks.TAPE_RECORDER.get(),
                        ModBlocks.SULFUR_ORE.get(),
                        ModBlocks.ALUMINUM_ORE.get(),
                        ModBlocks.DOOR_METAL.get(),
                        ModBlocks.PAINTABLE_COATED_UNIVERSAL_FLUID_DUCT.get(),
                        ModBlocks.STEEL_POLE.get(),
                        ModBlocks.TURBOFAN.get(),
                        ModBlocks.SHORT_RANGE_SIM_CARD_DATA_SENDER.get(),
                        ModBlocks.ADVANCED_RADIATION_ABSORBER.get(),
                        ModBlocks.INDUSTRIAL_BOILER.get(),
                        ModBlocks.INDUSTRIAL_COMBUSTION_GENERATOR.get(),
                        ModBlocks.CRUCIBLE.get(),
                        ModBlocks.DEUTERIUM_EXTRACTION_TOWER.get(),
                        ModBlocks.VACUUM_REFINERY.get(),
                        ModBlocks.PUMPJACK.get(),
                        ModBlocks.COMPRESSOR.get(),
                        ModBlocks.EXPOSURE_CHAMBER.get(),
                        ModBlocks.LARGE_MINING_DRILL.get(),
                        ModBlocks.CATALYTIC_REFORMER.get(),
                        ModBlocks.FLARE_STACK.get(),
                        ModBlocks.ELECTRIC_ARC_FURNACE.get(),
                        ModBlocks.LARGE_ELECTRICITY_PYLON.get(),
                        ModBlocks.ASSEMBLY_MACHINE.get(),
                        ModBlocks.STEAM_CONDENSER.get(),
                        ModBlocks.TUNGSTEN_ORE.get(),
                        ModBlocks.BURNER_PRESS.get(),
                        ModBlocks.QUARTZ_SAND.get(),
                        ModBlocks.QUARTZ_GLASS.get(),
                        ModBlocks.RADIATION_ABSORBER.get(),
                        ModBlocks.REINFORCED_STEEL_SCAFFOLD.get(),
                        ModBlocks.SILO_LAUNCH_PAD.get(),
                        ModBlocks.WOOD_BURNING_GENERATOR.get(),
                        ModBlocks.HEATING_OVEN.get(),
                        ModBlocks.ENHANCED_RADIATION_ABSORBER.get(),
                        ModBlocks.FIREBOX.get(),
                        ModBlocks.RARE_EARTH_ORE.get(),
                        ModBlocks.CHEMICAL_FACTORY.get(),
                        ModBlocks.FRACTIONATING_TOWER_SEPARATOR.get(),
                        ModBlocks.INDUSTRIAL_STEAM_TURBINE.get(),
                        ModBlocks.FRACTIONATING_TOWER.get(),
                        ModBlocks.CHEMICAL_PLANT.get(),
                        ModBlocks.ELITE_RADIATION_ABSORBER.get(),
                        ModBlocks.UNIVERSAL_FLUID_DUCT.get(),
                        ModBlocks.MATTER_GIGAFACTORY.get(),
                        ModBlocks.DRAINAGE_PIPE.get(),
                        ModBlocks.BATTERY_SOCKET.get(),
                        ModBlocks.REDSTONE_BATTERY.get(),
                        ModBlocks.OIL_REFINERY.get(),
                        ModBlocks.OIL_DERRICK.get(),
                        ModBlocks.ZIRNOX_NUCLEAR_REACTOR.get(),
                        ModBlocks.SCHRABIDIUM_BLOCK.get(),
                        ModBlocks.RADIOACTIVE_BARREL.get(),
                        ModBlocks.BLAST_FURNACE.get(),
                        ModBlocks.URANIUM_ORE.get(),
                        ModBlocks.LEAD_ORE.get(),
                        ModBlocks.CHLORINE_VENT.get(),
                        ModBlocks.CHLORINE_SEAL.get(),
                        ModBlocks.NUCLEAR_SIREN.get(),
                        ModBlocks.LITTLE_BOY.get(),
                        ModBlocks.MOLDY_DEBRIS.get(),
                        ModBlocks.CASTLE_BRAVO.get(),
                        ModBlocks.PWR_CONTROLLER.get(),
                        ModBlocks.STEEL_GRATE.get(),
                        ModBlocks.FLOURITE_ORE.get(),
                        ModBlocks.STEEL_SCAFFOLD.get(),
                        ModBlocks.CONVEYOR_LIFT.get(),
                        ModBlocks.CONVEYOR_CHAIN_LIFT.get(),
                        ModBlocks.REINFORCED_LAMP.get(),
                        ModBlocks.REINFORCED_SANDSTONE.get(),
                        ModBlocks.REINFORCED_GLOWSTONE.get(),
                        ModBlocks.LARGE_VINYL_TILE.get(),
                        ModBlocks.SMALL_VINYL_TILES.get(),
                        ModBlocks.ASPHALT.get(),
                        ModBlocks.GLOWING_ASPHALT.get(),
                        ModBlocks.FIREBRICKS.get(),
                        ModBlocks.LIGHT_BRICKS.get(),
                        ModBlocks.CRUSHED_OBSIDIAN.get(),
                        ModBlocks.MARKED_CONCRETE_BRICKS.get(),
                        ModBlocks.BROKEN_CONCRETE_BRICKS.get(),
                        ModBlocks.CRACKED_CONCRETE_BRICKS.get(),
                        ModBlocks.DENSE_STONE.get(),
                        ModBlocks.CONCRETE_TILE.get(),
                        ModBlocks.ASBESTOS_CONCRETE.get(),
                        ModBlocks.REBAR_REINFORCED_CONCRETE_PILLAR.get(),
                        ModBlocks.MOSSY_CONCRETE_BRICKS.get(),
                        ModBlocks.CMB_STEEL_TILE.get(),
                        ModBlocks.DUCRETE.get(),
                        ModBlocks.DUCRETE_TILE.get(),
                        ModBlocks.OBSIDIAN_BRICKS.get(),
                        ModBlocks.REINFORCED_STONE.get(),
                        ModBlocks.UBER_CONCRETE.get(),
                        ModBlocks.COMPOUND_MESH.get(),
                        ModBlocks.DUCRETE_BRICKS.get(),
                        ModBlocks.REINFORCED_DUCRETE.get(),
                        ModBlocks.IVY_MIKE.get(),
                        ModBlocks.TSAR_BOMBA.get(),
                        ModBlocks.FAT_MAN.get(),
                        ModBlocks.REINFORCED_CMB_BRICKS.get(),
                        ModBlocks.ORE_ACIDIZER.get(),
                        ModBlocks.CONVEYOR_SPLITTER.get(),
                        ModBlocks.COPPER_CABLE.get(),
                        ModBlocks.SOLDERING_STATION.get(),
                        ModBlocks.ARC_WELDER.get(),
                        ModBlocks.SMOKESTACK.get(),
                        ModBlocks.HYDRAULIC_FRACKING_TOWER.get(),
                        ModBlocks.TANK.get(),
                        ModBlocks.TITANIUM_ORE.get());
    }
}
